spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-link-dev

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-link-test